/***************************************************************************

 TextEditor.mcc - Textediting MUI Custom Class
 Copyright (C) 1997-2000 Allan Odgaard
 Copyright (C) 2005 by TextEditor.mcc Open Source Team

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 TextEditor class Support Site:  http://www.sf.net/projects/texteditor-mcc

 $Id$

***************************************************************************/

/****************************************************************
***
*** Main c file for locale
***
*** This file has been generated by Localizer 1.0
***
*****************************************************************/

#include <libraries/locale.h>
#include <proto/locale.h>

static LONG CatVersion = 2;

#if defined(__amigaos4__) || defined(__MORPHOS__)
extern struct Library *LocaleBase;
#else
extern struct LocaleBase *LocaleBase;
#endif

struct LocStr
{
    LONG   ID;
    STRPTR Str;
};

const struct LocStr _HelpBubble_BlockQual = {0,"Move the cursor key and hold down the qualifer\nthat you set here to mark text."};
const struct LocStr _HelpBubble_CheckWord = {1,"If enabled, then the editor will lookup the word,\nand only show suggestions if the word is misspelled."};
const struct LocStr _HelpBubble_Smooth = {2,"This will enable pixel smooth scrolling."};
const struct LocStr _HelpBubble_TypeNSpell = {3,"Enable this to let the editor\nlookup the words while you type them."};
const struct LocStr _HelpBubble_UndoLevel = {4,"Each undo eats 10 bytes of memory.\nCut and Copy takes a little more,\ndepends on the block size!"};
const struct LocStr _MSG_Button_DefaultKeys = {5,"Default _keys"};
const struct LocStr _MSG_Button_Delete = {6,"_Delete"};
const struct LocStr _MSG_Button_Insert = {7,"_Insert"};
const struct LocStr _MSG_Button_Snoop = {123,"Snoop"};
const struct LocStr _MSG_ConfigMenu_CheckWord = {8,"Check word"};
const struct LocStr _MSG_ConfigMenu_TypeNSpell = {9,"Type'n'spell"};
const struct LocStr _MSG_CycleItem_Alt = {10,"Alt"};
const struct LocStr _MSG_CycleItem_Ctrl = {11,"Control"};
const struct LocStr _MSG_CycleItem_Mouse = {12,"(mouse only)"};
const struct LocStr _MSG_CycleItem_Shift = {13,"Shift"};
const struct LocStr _MSG_Execution_ARexx = {14,"ARexx"};
const struct LocStr _MSG_Execution_CLI = {15,"CLI"};
const struct LocStr _MSG_Function_BOL = {16,"Begin Of Line"};
const struct LocStr _MSG_Function_Backspace = {17,"Backspace"};
const struct LocStr _MSG_Function_Bottom = {18,"Bottom"};
const struct LocStr _MSG_Function_Copy = {19,"Copy"};
const struct LocStr _MSG_Function_Cut = {20,"Cut"};
const struct LocStr _MSG_Function_DelBOL = {21,"Delete to BOL"};
const struct LocStr _MSG_Function_DelBOW = {22,"Delete to BOW"};
const struct LocStr _MSG_Function_DelEOL = {23,"Delete to EOL"};
const struct LocStr _MSG_Function_DelEOW = {24,"Delete to EOW"};
const struct LocStr _MSG_Function_DelLine = {124,"Delete line"};
const struct LocStr _MSG_Function_Delete = {25,"Delete"};
const struct LocStr _MSG_Function_Down = {26,"Down"};
const struct LocStr _MSG_Function_EOL = {27,"End Of Line"};
const struct LocStr _MSG_Function_GotoBookmark1 = {117,"Goto Bookmark 1"};
const struct LocStr _MSG_Function_GotoBookmark2 = {118,"Goto Bookmark 2"};
const struct LocStr _MSG_Function_GotoBookmark3 = {119,"Goto Bookmark 3"};
const struct LocStr _MSG_Function_Left = {28,"Left"};
const struct LocStr _MSG_Function_NextGadget = {29,"Next gadget"};
const struct LocStr _MSG_Function_NxtPage = {30,"Next Page"};
const struct LocStr _MSG_Function_NxtPara = {31,"Next Paragraph"};
const struct LocStr _MSG_Function_NxtSent = {32,"Next Sentence"};
const struct LocStr _MSG_Function_NxtWord = {33,"Next Word"};
const struct LocStr _MSG_Function_Paste = {34,"Paste"};
const struct LocStr _MSG_Function_PrvPage = {35,"Prev Page"};
const struct LocStr _MSG_Function_PrvPara = {36,"Prev Paragraph"};
const struct LocStr _MSG_Function_PrvSent = {37,"Prev Sentence"};
const struct LocStr _MSG_Function_PrvWord = {38,"Prev Word"};
const struct LocStr _MSG_Function_Redo = {39,"Redo"};
const struct LocStr _MSG_Function_Return = {40,"Return"};
const struct LocStr _MSG_Function_Right = {41,"Right"};
const struct LocStr _MSG_Function_SetBookmark1 = {120,"Set Bookmark 1"};
const struct LocStr _MSG_Function_SetBookmark2 = {121,"Set Bookmark 2"};
const struct LocStr _MSG_Function_SetBookmark3 = {122,"Set Bookmark 3"};
const struct LocStr _MSG_Function_SuggestSpelling = {42,"Suggest spelling"};
const struct LocStr _MSG_Function_Tab = {43,"Tab"};
const struct LocStr _MSG_Function_Top = {44,"Top"};
const struct LocStr _MSG_Function_Undo = {45,"Undo"};
const struct LocStr _MSG_Function_Up = {46,"Up"};
const struct LocStr _MSG_GroupTitle_Control = {47,"Control"};
const struct LocStr _MSG_GroupTitle_Cursor = {48,"Cursor"};
const struct LocStr _MSG_GroupTitle_Design = {49,"Design"};
const struct LocStr _MSG_GroupTitle_Fonts = {50,"Fonts"};
const struct LocStr _MSG_GroupTitle_Separator = {51,"Separator"};
const struct LocStr _MSG_HelpTxt_SpellChecker = {52," \33u Intro \33n\n\nThe TextEditor gadget offers you easy integration of external spell checkers, this allows you to have both type'n'spell and also normal "
                                                    "word-guessing.\n\n \33u Lookup command \33n\n\nFor the type'n'spell you'll have to set the lookup command to a script that will lookup the word and set the environment variable \"Found\" to either 0 (for not found) or 1 (for a match).\nI have chosen this behavior because it is the default for AlphaSpell.\nYou write %s where you want the word.\nIf you use AlphaSpell, then you can write:\n\33bARexx:\33n \"Options Results;Address ALPHASPELL Search For '%s' Path 'T:' Danish.ald\"\n\nYou \33bmust\33n remember the quotes, this will let ARexx execute it as a command instead of a script.\n\n \33u Suggest command \33n\n\nIf you press HELP over a word, then the editor will launch this command, again with %s substituted with the current word.\nYour script should produce a file in T: named \"Matches\". This file are then read by the gadget, and the contents are shown in a popup-listview, from where you can choose a word "
                                                    "which will replace the misspelled one.\nAgain, AlphaSpell users can "
                                                    "write:\n\33bARexx:\33n \"Options Results;Address ALPHASPELL Match '%s' To 'T:Matches' Path 'T:' Danish.ald\"\n\nIf you use the methods described above, "
                                                    "then you must start AlphaSpell with the \"ARexx\" switch.\n\nIt is advised to keep your dictionary in RAM if you enable the type'n'spell feature."};
const struct LocStr _MSG_LVLabel_Action = {53,"\33c\0333Action:"};
const struct LocStr _MSG_LVLabel_Key = {54,"\33c\0333Key:"};
const struct LocStr _MSG_Label_Background = {55,"Background"};
const struct LocStr _MSG_Label_BlinkSpeed = {56,"Blinkspeed"};
const struct LocStr _MSG_Label_BlkQual = {57,"Block qualifier"};
const struct LocStr _MSG_Label_Cursor = {58,"Cursor"};
const struct LocStr _MSG_Label_Fixed = {59,"Fixed"};
const struct LocStr _MSG_Label_Frame = {60,"Frame"};
const struct LocStr _MSG_Label_Highlight = {61,"Highlight"};
const struct LocStr _MSG_Label_LookupCmd = {62,"Lookup command"};
const struct LocStr _MSG_Label_LookupWords = {63,"Lookup word before suggesting?"};
const struct LocStr _MSG_Label_Normal = {64,"Normal"};
const struct LocStr _MSG_Label_Selected = {65,"Selected"};
const struct LocStr _MSG_Label_SeparatorShadow = {66,"Shadow"};
const struct LocStr _MSG_Label_SeparatorShine = {67,"Shine"};
const struct LocStr _MSG_Label_Smooth = {68,"Smooth"};
const struct LocStr _MSG_Label_SpellNType = {69,"Spell check as you type?"};
const struct LocStr _MSG_Label_SuggestCmd = {70,"Suggest command"};
const struct LocStr _MSG_Label_TabSize = {71,"Tab size"};
const struct LocStr _MSG_Label_Text = {72,"Text"};
const struct LocStr _MSG_Label_UndoLevel = {73,"Undo levels"};
const struct LocStr _MSG_Label_Width = {74,"Width"};
const struct LocStr _MSG_MenuItem_Background = {75,"Background"};
const struct LocStr _MSG_MenuItem_Bold = {76,"Bold"};
const struct LocStr _MSG_MenuItem_Center = {77,"Center"};
const struct LocStr _MSG_MenuItem_Copy = {78,"Copy"};
const struct LocStr _MSG_MenuItem_Cut = {79,"Cut"};
const struct LocStr _MSG_MenuItem_Delete = {80,"Delete"};
const struct LocStr _MSG_MenuItem_Fill = {81,"Fill"};
const struct LocStr _MSG_MenuItem_Halfshadow = {82,"Halfshadow"};
const struct LocStr _MSG_MenuItem_Halfshine = {83,"Halfshine"};
const struct LocStr _MSG_MenuItem_Italic = {84,"Italic"};
const struct LocStr _MSG_MenuItem_Left = {85,"Left"};
const struct LocStr _MSG_MenuItem_Mark = {86,"Mark"};
const struct LocStr _MSG_MenuItem_Normal = {87,"Normal"};
const struct LocStr _MSG_MenuItem_Paste = {88,"Paste"};
const struct LocStr _MSG_MenuItem_Redo = {89,"Redo"};
const struct LocStr _MSG_MenuItem_Right = {90,"Right"};
const struct LocStr _MSG_MenuItem_Shadow = {91,"Shadow"};
const struct LocStr _MSG_MenuItem_Shine = {92,"Shine"};
const struct LocStr _MSG_MenuItem_Text = {93,"Text"};
const struct LocStr _MSG_MenuItem_Underline = {94,"Underline"};
const struct LocStr _MSG_MenuItem_Undo = {95,"Undo"};
const struct LocStr _MSG_MenuSubTitle_Alignment = {96,"Alignment"};
const struct LocStr _MSG_MenuSubTitle_Color = {97,"Color"};
const struct LocStr _MSG_MenuTitle_Edit = {98,"Edit"};
const struct LocStr _MSG_Page_Keybindings = {99,"Keybindings"};
const struct LocStr _MSG_Page_Sample = {100,"Sample"};
const struct LocStr _MSG_Page_Settings = {101,"Settings"};
const struct LocStr _MSG_Page_SpellChecker = {102,"Spell checker"};
const struct LocStr _MSG_PopWinTitle_Background = {103,"Select background"};
const struct LocStr _MSG_PopWinTitle_Cursor = {104,"Select cursor color"};
const struct LocStr _MSG_PopWinTitle_Frame = {105,"Select frame"};
const struct LocStr _MSG_PopWinTitle_Highlight = {106,"Select highlight color"};
const struct LocStr _MSG_PopWinTitle_Selected = {107,"Select block color"};
const struct LocStr _MSG_PopWinTitle_SeparatorShadow = {108,"Select separators shadow color"};
const struct LocStr _MSG_PopWinTitle_SeparatorShine = {109,"Select separators shine color"};
const struct LocStr _MSG_PopWinTitle_Text = {110,"Select text color"};
const struct LocStr _MSG_SliderText_MaxWidth = {111,"Same as char"};
const struct LocStr _MSG_SliderText_MinSpeed = {112,"Off"};
const struct LocStr _MSG_SliderText_MinWidth = {113,"1 pixel"};
const struct LocStr _MSG_SliderText_StdSpeed = {114,"\33r%ld ms"};
const struct LocStr _MSG_SliderText_StdWidth = {115,"%ld pixels"};
const struct LocStr _MSG_SliderText_TabSize = {116,"%ld spaces"};

static struct Catalog *Catalog = NULL;

/******************************************************************************/
void OpenCat(struct Locale *);
void CloseCat(void);
STRPTR GetString(APTR);

/******************************************************************************/

void OpenCat(struct Locale * Loc)
{
    if(LocaleBase != NULL && Catalog == NULL)
    {
        Catalog=OpenCatalog(Loc,(STRPTR)"TextEditor_mcp.catalog",
                            OC_BuiltInLanguage,"english",
                            OC_Version,CatVersion,
                            TAG_DONE);
    }
}

void CloseCat(void)
{
    if(LocaleBase!=NULL)
    {
        CloseCatalog(Catalog);
    }
    Catalog=NULL;
}

STRPTR GetString(APTR CatStr)
{
    STRPTR DefStr;
    LONG StrNum;

    StrNum=((struct LocStr *)CatStr)->ID;
    DefStr=((struct LocStr *) CatStr)->Str;

    return(Catalog ? (STRPTR)GetCatalogStr(Catalog,StrNum,DefStr) : DefStr);
}
