/***************************************************************************

 TextEditor.mcc - Textediting MUI Custom Class
 Copyright (C) 1997-2000 Allan Odgaard
 Copyright (C) 2005 by TextEditor.mcc Open Source Team

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 TextEditor class Support Site:  http://www.sf.net/projects/texteditor-mcc

 $Id$

***************************************************************************/

#include <proto/locale.h>

/****************************************************************
***
*** Include file for locale
***
*** This file has been generated by Localizer
***
*****************************************************************/

extern void OpenCat(struct Locale *);
extern void CloseCat(void);
extern STRPTR GetString(APTR);

/******************************************************************************/

#define CatString(a,b) GetString(a)
extern const APTR _HelpBubble_BlockQual;
#define HelpBubble_BlockQual ((APTR) &_HelpBubble_BlockQual)
extern const APTR _HelpBubble_CheckWord;
#define HelpBubble_CheckWord ((APTR) &_HelpBubble_CheckWord)
extern const APTR _HelpBubble_Smooth;
#define HelpBubble_Smooth ((APTR) &_HelpBubble_Smooth)
extern const APTR _HelpBubble_TypeNSpell;
#define HelpBubble_TypeNSpell ((APTR) &_HelpBubble_TypeNSpell)
extern const APTR _HelpBubble_UndoLevel;
#define HelpBubble_UndoLevel ((APTR) &_HelpBubble_UndoLevel)
extern const APTR _MSG_Button_DefaultKeys;
#define MSG_Button_DefaultKeys ((APTR) &_MSG_Button_DefaultKeys)
extern const APTR _MSG_Button_Delete;
#define MSG_Button_Delete ((APTR) &_MSG_Button_Delete)
extern const APTR _MSG_Button_Insert;
#define MSG_Button_Insert ((APTR) &_MSG_Button_Insert)
extern const APTR _MSG_Button_Snoop;
#define MSG_Button_Snoop ((APTR) &_MSG_Button_Snoop)
extern const APTR _MSG_ConfigMenu_CheckWord;
#define MSG_ConfigMenu_CheckWord ((APTR) &_MSG_ConfigMenu_CheckWord)
extern const APTR _MSG_ConfigMenu_TypeNSpell;
#define MSG_ConfigMenu_TypeNSpell ((APTR) &_MSG_ConfigMenu_TypeNSpell)
extern const APTR _MSG_CycleItem_Alt;
#define MSG_CycleItem_Alt ((APTR) &_MSG_CycleItem_Alt)
extern const APTR _MSG_CycleItem_Ctrl;
#define MSG_CycleItem_Ctrl ((APTR) &_MSG_CycleItem_Ctrl)
extern const APTR _MSG_CycleItem_Mouse;
#define MSG_CycleItem_Mouse ((APTR) &_MSG_CycleItem_Mouse)
extern const APTR _MSG_CycleItem_Shift;
#define MSG_CycleItem_Shift ((APTR) &_MSG_CycleItem_Shift)
extern const APTR _MSG_Execution_ARexx;
#define MSG_Execution_ARexx ((APTR) &_MSG_Execution_ARexx)
extern const APTR _MSG_Execution_CLI;
#define MSG_Execution_CLI ((APTR) &_MSG_Execution_CLI)
extern const APTR _MSG_Function_BOL;
#define MSG_Function_BOL ((APTR) &_MSG_Function_BOL)
extern const APTR _MSG_Function_Backspace;
#define MSG_Function_Backspace ((APTR) &_MSG_Function_Backspace)
extern const APTR _MSG_Function_Bottom;
#define MSG_Function_Bottom ((APTR) &_MSG_Function_Bottom)
extern const APTR _MSG_Function_Copy;
#define MSG_Function_Copy ((APTR) &_MSG_Function_Copy)
extern const APTR _MSG_Function_Cut;
#define MSG_Function_Cut ((APTR) &_MSG_Function_Cut)
extern const APTR _MSG_Function_DelBOL;
#define MSG_Function_DelBOL ((APTR) &_MSG_Function_DelBOL)
extern const APTR _MSG_Function_DelBOW;
#define MSG_Function_DelBOW ((APTR) &_MSG_Function_DelBOW)
extern const APTR _MSG_Function_DelEOL;
#define MSG_Function_DelEOL ((APTR) &_MSG_Function_DelEOL)
extern const APTR _MSG_Function_DelEOW;
#define MSG_Function_DelEOW ((APTR) &_MSG_Function_DelEOW)
extern const APTR _MSG_Function_DelLine;
#define MSG_Function_DelLine ((APTR) &_MSG_Function_DelLine)
extern const APTR _MSG_Function_Delete;
#define MSG_Function_Delete ((APTR) &_MSG_Function_Delete)
extern const APTR _MSG_Function_Down;
#define MSG_Function_Down ((APTR) &_MSG_Function_Down)
extern const APTR _MSG_Function_EOL;
#define MSG_Function_EOL ((APTR) &_MSG_Function_EOL)
extern const APTR _MSG_Function_GotoBookmark1;
#define MSG_Function_GotoBookmark1 ((APTR) &_MSG_Function_GotoBookmark1)
extern const APTR _MSG_Function_GotoBookmark2;
#define MSG_Function_GotoBookmark2 ((APTR) &_MSG_Function_GotoBookmark2)
extern const APTR _MSG_Function_GotoBookmark3;
#define MSG_Function_GotoBookmark3 ((APTR) &_MSG_Function_GotoBookmark3)
extern const APTR _MSG_Function_Left;
#define MSG_Function_Left ((APTR) &_MSG_Function_Left)
extern const APTR _MSG_Function_NextGadget;
#define MSG_Function_NextGadget ((APTR) &_MSG_Function_NextGadget)
extern const APTR _MSG_Function_NxtPage;
#define MSG_Function_NxtPage ((APTR) &_MSG_Function_NxtPage)
extern const APTR _MSG_Function_NxtPara;
#define MSG_Function_NxtPara ((APTR) &_MSG_Function_NxtPara)
extern const APTR _MSG_Function_NxtSent;
#define MSG_Function_NxtSent ((APTR) &_MSG_Function_NxtSent)
extern const APTR _MSG_Function_NxtWord;
#define MSG_Function_NxtWord ((APTR) &_MSG_Function_NxtWord)
extern const APTR _MSG_Function_Paste;
#define MSG_Function_Paste ((APTR) &_MSG_Function_Paste)
extern const APTR _MSG_Function_PrvPage;
#define MSG_Function_PrvPage ((APTR) &_MSG_Function_PrvPage)
extern const APTR _MSG_Function_PrvPara;
#define MSG_Function_PrvPara ((APTR) &_MSG_Function_PrvPara)
extern const APTR _MSG_Function_PrvSent;
#define MSG_Function_PrvSent ((APTR) &_MSG_Function_PrvSent)
extern const APTR _MSG_Function_PrvWord;
#define MSG_Function_PrvWord ((APTR) &_MSG_Function_PrvWord)
extern const APTR _MSG_Function_Redo;
#define MSG_Function_Redo ((APTR) &_MSG_Function_Redo)
extern const APTR _MSG_Function_Return;
#define MSG_Function_Return ((APTR) &_MSG_Function_Return)
extern const APTR _MSG_Function_Right;
#define MSG_Function_Right ((APTR) &_MSG_Function_Right)
extern const APTR _MSG_Function_SetBookmark1;
#define MSG_Function_SetBookmark1 ((APTR) &_MSG_Function_SetBookmark1)
extern const APTR _MSG_Function_SetBookmark2;
#define MSG_Function_SetBookmark2 ((APTR) &_MSG_Function_SetBookmark2)
extern const APTR _MSG_Function_SetBookmark3;
#define MSG_Function_SetBookmark3 ((APTR) &_MSG_Function_SetBookmark3)
extern const APTR _MSG_Function_SuggestSpelling;
#define MSG_Function_SuggestSpelling ((APTR) &_MSG_Function_SuggestSpelling)
extern const APTR _MSG_Function_Tab;
#define MSG_Function_Tab ((APTR) &_MSG_Function_Tab)
extern const APTR _MSG_Function_Top;
#define MSG_Function_Top ((APTR) &_MSG_Function_Top)
extern const APTR _MSG_Function_Undo;
#define MSG_Function_Undo ((APTR) &_MSG_Function_Undo)
extern const APTR _MSG_Function_Up;
#define MSG_Function_Up ((APTR) &_MSG_Function_Up)
extern const APTR _MSG_GroupTitle_Control;
#define MSG_GroupTitle_Control ((APTR) &_MSG_GroupTitle_Control)
extern const APTR _MSG_GroupTitle_Cursor;
#define MSG_GroupTitle_Cursor ((APTR) &_MSG_GroupTitle_Cursor)
extern const APTR _MSG_GroupTitle_Design;
#define MSG_GroupTitle_Design ((APTR) &_MSG_GroupTitle_Design)
extern const APTR _MSG_GroupTitle_Fonts;
#define MSG_GroupTitle_Fonts ((APTR) &_MSG_GroupTitle_Fonts)
extern const APTR _MSG_GroupTitle_Separator;
#define MSG_GroupTitle_Separator ((APTR) &_MSG_GroupTitle_Separator)
extern const APTR _MSG_HelpTxt_SpellChecker;
#define MSG_HelpTxt_SpellChecker ((APTR) &_MSG_HelpTxt_SpellChecker)
extern const APTR _MSG_LVLabel_Action;
#define MSG_LVLabel_Action ((APTR) &_MSG_LVLabel_Action)
extern const APTR _MSG_LVLabel_Key;
#define MSG_LVLabel_Key ((APTR) &_MSG_LVLabel_Key)
extern const APTR _MSG_Label_Background;
#define MSG_Label_Background ((APTR) &_MSG_Label_Background)
extern const APTR _MSG_Label_BlinkSpeed;
#define MSG_Label_BlinkSpeed ((APTR) &_MSG_Label_BlinkSpeed)
extern const APTR _MSG_Label_BlkQual;
#define MSG_Label_BlkQual ((APTR) &_MSG_Label_BlkQual)
extern const APTR _MSG_Label_Cursor;
#define MSG_Label_Cursor ((APTR) &_MSG_Label_Cursor)
extern const APTR _MSG_Label_Fixed;
#define MSG_Label_Fixed ((APTR) &_MSG_Label_Fixed)
extern const APTR _MSG_Label_Frame;
#define MSG_Label_Frame ((APTR) &_MSG_Label_Frame)
extern const APTR _MSG_Label_Highlight;
#define MSG_Label_Highlight ((APTR) &_MSG_Label_Highlight)
extern const APTR _MSG_Label_LookupCmd;
#define MSG_Label_LookupCmd ((APTR) &_MSG_Label_LookupCmd)
extern const APTR _MSG_Label_LookupWords;
#define MSG_Label_LookupWords ((APTR) &_MSG_Label_LookupWords)
extern const APTR _MSG_Label_Normal;
#define MSG_Label_Normal ((APTR) &_MSG_Label_Normal)
extern const APTR _MSG_Label_Selected;
#define MSG_Label_Selected ((APTR) &_MSG_Label_Selected)
extern const APTR _MSG_Label_SeparatorShadow;
#define MSG_Label_SeparatorShadow ((APTR) &_MSG_Label_SeparatorShadow)
extern const APTR _MSG_Label_SeparatorShine;
#define MSG_Label_SeparatorShine ((APTR) &_MSG_Label_SeparatorShine)
extern const APTR _MSG_Label_Smooth;
#define MSG_Label_Smooth ((APTR) &_MSG_Label_Smooth)
extern const APTR _MSG_Label_SpellNType;
#define MSG_Label_SpellNType ((APTR) &_MSG_Label_SpellNType)
extern const APTR _MSG_Label_SuggestCmd;
#define MSG_Label_SuggestCmd ((APTR) &_MSG_Label_SuggestCmd)
extern const APTR _MSG_Label_TabSize;
#define MSG_Label_TabSize ((APTR) &_MSG_Label_TabSize)
extern const APTR _MSG_Label_Text;
#define MSG_Label_Text ((APTR) &_MSG_Label_Text)
extern const APTR _MSG_Label_UndoLevel;
#define MSG_Label_UndoLevel ((APTR) &_MSG_Label_UndoLevel)
extern const APTR _MSG_Label_Width;
#define MSG_Label_Width ((APTR) &_MSG_Label_Width)
extern const APTR _MSG_MenuItem_Background;
#define MSG_MenuItem_Background ((APTR) &_MSG_MenuItem_Background)
extern const APTR _MSG_MenuItem_Bold;
#define MSG_MenuItem_Bold ((APTR) &_MSG_MenuItem_Bold)
extern const APTR _MSG_MenuItem_Center;
#define MSG_MenuItem_Center ((APTR) &_MSG_MenuItem_Center)
extern const APTR _MSG_MenuItem_Copy;
#define MSG_MenuItem_Copy ((APTR) &_MSG_MenuItem_Copy)
extern const APTR _MSG_MenuItem_Cut;
#define MSG_MenuItem_Cut ((APTR) &_MSG_MenuItem_Cut)
extern const APTR _MSG_MenuItem_Delete;
#define MSG_MenuItem_Delete ((APTR) &_MSG_MenuItem_Delete)
extern const APTR _MSG_MenuItem_Fill;
#define MSG_MenuItem_Fill ((APTR) &_MSG_MenuItem_Fill)
extern const APTR _MSG_MenuItem_Halfshadow;
#define MSG_MenuItem_Halfshadow ((APTR) &_MSG_MenuItem_Halfshadow)
extern const APTR _MSG_MenuItem_Halfshine;
#define MSG_MenuItem_Halfshine ((APTR) &_MSG_MenuItem_Halfshine)
extern const APTR _MSG_MenuItem_Italic;
#define MSG_MenuItem_Italic ((APTR) &_MSG_MenuItem_Italic)
extern const APTR _MSG_MenuItem_Left;
#define MSG_MenuItem_Left ((APTR) &_MSG_MenuItem_Left)
extern const APTR _MSG_MenuItem_Mark;
#define MSG_MenuItem_Mark ((APTR) &_MSG_MenuItem_Mark)
extern const APTR _MSG_MenuItem_Normal;
#define MSG_MenuItem_Normal ((APTR) &_MSG_MenuItem_Normal)
extern const APTR _MSG_MenuItem_Paste;
#define MSG_MenuItem_Paste ((APTR) &_MSG_MenuItem_Paste)
extern const APTR _MSG_MenuItem_Redo;
#define MSG_MenuItem_Redo ((APTR) &_MSG_MenuItem_Redo)
extern const APTR _MSG_MenuItem_Right;
#define MSG_MenuItem_Right ((APTR) &_MSG_MenuItem_Right)
extern const APTR _MSG_MenuItem_Shadow;
#define MSG_MenuItem_Shadow ((APTR) &_MSG_MenuItem_Shadow)
extern const APTR _MSG_MenuItem_Shine;
#define MSG_MenuItem_Shine ((APTR) &_MSG_MenuItem_Shine)
extern const APTR _MSG_MenuItem_Text;
#define MSG_MenuItem_Text ((APTR) &_MSG_MenuItem_Text)
extern const APTR _MSG_MenuItem_Underline;
#define MSG_MenuItem_Underline ((APTR) &_MSG_MenuItem_Underline)
extern const APTR _MSG_MenuItem_Undo;
#define MSG_MenuItem_Undo ((APTR) &_MSG_MenuItem_Undo)
extern const APTR _MSG_MenuSubTitle_Alignment;
#define MSG_MenuSubTitle_Alignment ((APTR) &_MSG_MenuSubTitle_Alignment)
extern const APTR _MSG_MenuSubTitle_Color;
#define MSG_MenuSubTitle_Color ((APTR) &_MSG_MenuSubTitle_Color)
extern const APTR _MSG_MenuTitle_Edit;
#define MSG_MenuTitle_Edit ((APTR) &_MSG_MenuTitle_Edit)
extern const APTR _MSG_Page_Keybindings;
#define MSG_Page_Keybindings ((APTR) &_MSG_Page_Keybindings)
extern const APTR _MSG_Page_Sample;
#define MSG_Page_Sample ((APTR) &_MSG_Page_Sample)
extern const APTR _MSG_Page_Settings;
#define MSG_Page_Settings ((APTR) &_MSG_Page_Settings)
extern const APTR _MSG_Page_SpellChecker;
#define MSG_Page_SpellChecker ((APTR) &_MSG_Page_SpellChecker)
extern const APTR _MSG_PopWinTitle_Background;
#define MSG_PopWinTitle_Background ((APTR) &_MSG_PopWinTitle_Background)
extern const APTR _MSG_PopWinTitle_Cursor;
#define MSG_PopWinTitle_Cursor ((APTR) &_MSG_PopWinTitle_Cursor)
extern const APTR _MSG_PopWinTitle_Frame;
#define MSG_PopWinTitle_Frame ((APTR) &_MSG_PopWinTitle_Frame)
extern const APTR _MSG_PopWinTitle_Highlight;
#define MSG_PopWinTitle_Highlight ((APTR) &_MSG_PopWinTitle_Highlight)
extern const APTR _MSG_PopWinTitle_Selected;
#define MSG_PopWinTitle_Selected ((APTR) &_MSG_PopWinTitle_Selected)
extern const APTR _MSG_PopWinTitle_SeparatorShadow;
#define MSG_PopWinTitle_SeparatorShadow ((APTR) &_MSG_PopWinTitle_SeparatorShadow)
extern const APTR _MSG_PopWinTitle_SeparatorShine;
#define MSG_PopWinTitle_SeparatorShine ((APTR) &_MSG_PopWinTitle_SeparatorShine)
extern const APTR _MSG_PopWinTitle_Text;
#define MSG_PopWinTitle_Text ((APTR) &_MSG_PopWinTitle_Text)
extern const APTR _MSG_SliderText_MaxWidth;
#define MSG_SliderText_MaxWidth ((APTR) &_MSG_SliderText_MaxWidth)
extern const APTR _MSG_SliderText_MinSpeed;
#define MSG_SliderText_MinSpeed ((APTR) &_MSG_SliderText_MinSpeed)
extern const APTR _MSG_SliderText_MinWidth;
#define MSG_SliderText_MinWidth ((APTR) &_MSG_SliderText_MinWidth)
extern const APTR _MSG_SliderText_StdSpeed;
#define MSG_SliderText_StdSpeed ((APTR) &_MSG_SliderText_StdSpeed)
extern const APTR _MSG_SliderText_StdWidth;
#define MSG_SliderText_StdWidth ((APTR) &_MSG_SliderText_StdWidth)
extern const APTR _MSG_SliderText_TabSize;
#define MSG_SliderText_TabSize ((APTR) &_MSG_SliderText_TabSize)
